{
        "_plugin": {
            "INSTALL_DESC": "Install external plugins.",
            "NEED_URL": "Please enter a URL! Example:",
            "UNOFF": "⚠️ *Attention!* \n*The plugin you have installed is not official!*",
            "INVALID_URL": "```Please enter a valid url!```",
            "INVALID_PLUGIN": "*❌ Your plugin is invalid!*\n*Error:*",
            "INSTALLED": "*✅ Plugin has been successfully installed!*",
            "PLUGIN_DESC": "Shows the plugins you have installed.",
            "INSTALLED_FROM_REMOTE": "*Plugins you install externally:*\n",
            "NO_PLUGIN": "*You have not installed any external plugins!*",
            "REMOVE_DESC": "Removes the plugin.",
            "NEED_PLUGIN": "```Please enter a Plugin! Example: .plugin __test```",
            "NOT_FOUND_PLUGIN": "```Maybe you have installed such a plugin, or maybe not. But it sure isn't right now.```",
            "DELETED": "*✅ Module successfully deleted!*",
            "WARN": "Get plugins only from t.me/remasterplugin channel."
        },
        "filters": {
            "FILTER_DESC": "It adds a filter. If someone writes your filter, it send the answer. If you just write .filter, it show's your filter list.",
            "NO_FILTER": "*❌ There are no filters in this chat!*",
            "FILTERS": "*🔎 There is your filters in this chat:*",
            "NEED_REPLY": "*❌ Please type in reply!*\n*Example:*",
            "FILTERED": "*✅ Successfully set* ```{}``` *to filter!*",
            "STOP_DESC": "Stops the filter you added previously.",
            "NEED_FILTER": "*❌ Please type a filter!*\n*Example:*",
            "ALREADY_NO_FILTER": "*❌ There is already no filter like this!*",
            "DELETED": "*✅ The filter was successfully deleted!*"
        },
        "greetings": {
            "WELCOME_DESC": "It sets the welcome message. If you leave it blank it shows the welcome message.",
            "NOT_SET_WELCOME": "*You don't set the welcome message yet.!*\n**To set:** ```.welcome hi && hi#how are you?```",
            "WELCOME_ALREADY_SETTED": "*✅ Welcome message already set!*\n*Message:* ```",
            "NEED_WELCOME_TEXT": "*You must write a message to set up the welcome message.*\n*Example:* ```.welcome hi && hi#how are you?```",
            "WELCOME_DELETED": "*✅ Welcome message has been deleted successfully!*",
            "WELCOME_SETTED": "*✅ Welcome message has been set successfully!*",
            "PLKADMIN": ".report you are not admin \n\n 🇩​🇴​🇳​🇹​ 🇹​🇷​🇾​ 🇦​🇬​🇦​🇮​🇳​ 🇮​🇫​ 🇾​🇴​🇺​ 🇹​🇷​🇾​ 🇾​🇴​🇺​ 🇼​🇮​🇱​🇱​ 🇧​🇪​ 🇷​🇪​🇲​🇴​🇻​🇪​🇩​ 🇧​🇾​ 🇦​🇩​🇲​🇮​🇳​🇸​",
            "GOODBYE_DESC": "Sets the goodbye message. If you leave blank, it show's the goodbye message.",
            "NOT_SET_GOODBYE": "*You didn't set a goodbye message!*\n*To set:* ```.goodbye bye && bye#see ya```",
            "GOODBYE_ALREADY_SETTED": "*✅ Goodbye message has been set!*\n*Message:* ```",
            "NEED_GOODBYE_TEXT": "*You must write a message to set up the goodbye message.*\n*Example:* ```.goodbye bye && bye#see ya```",
            "GOODBYE_DELETED": "*✅ Goodbye message has been deleted successfully!*",
            "GOODBYE_SETTED": "*✅ Goodbye message has been setted successfully!*"
        }, 
        "updater": {
            "UPDATER_DESC": "Checks the update.",
            "UPDATE": "*Bot ɪs ᴀʟʀᴇᴀᴅʏ ᴜᴘᴅᴀᴛᴇᴅ ʙʀᴏ💝*",
            "NEW_UPDATE": "*New update available for Bot!*\n\n*To update Bot give this command: .update now*\n\n*Ask support group and update*\n*https://chat.whatsapp.com/KJWUNpT7lBzDuPGnlV69Vp*\n\nChanges:\n```",
            "UPDATE_NOW_DESC": "It makes updates.",
            "UPDATING": "Bot ᴜᴘᴅᴀᴛɪɴɢ...ᴘʟs ᴡ8 ʙʀᴏ💞",
            "INVALID_HEROKU": "*❌ Your Heroku app name or api key wrong!*",
            "UPDATED": "*successful Update Bot😍*",
            "UPDATED_LOCAL": "*✅ Updated!*",
            "AFTER_UPDATE": "Bot ʀᴇsᴛᴀʀᴛɪɴɢ... ᴘʟs ᴡ8 ʙʀᴏ💞",
            "IN_AF": "*Please check* ```HEROKU_APP_NAME``` *and* ```app name``` *They must be same.*\n*If these two values ​​are the same, please restore* ```HEROKU_API_KEY```\n\n_To access these settings, use Heroku >> App >> Settings >> Reavel Config Vars_\n_To renew your API key, follow these steps, Heroku >> Account >> API Key then replace old api key in config vars._"
        },
        "heroku": {
            "RESTART_DESC": "Restart Bot",
            "RESTART_MSG": "*Helo Master* 🥰\n\n*I Am Restarting Please Wait It Will Take 5 Minuit*",
            "SHUTDOWN_DESC": "Shutdown Bot",
            "SHUTDOWN_MSG": "*Ok Bye I Am Sleeping Now* 💤\n\n*Shuting Down* ⚠️",
            "DYNO_DESC": "Check heroku dyno usage",
            "DYNO_TOTAL": "```Total Quota```",
            "DYNO_USED": "```Quota used```",
            "PERCENTAGE": "```Percentage```",
            "DYNO_LEFT": "```Remaining```",
            "GR_DEL": "*Greetings Message Set!*\n*Type* ```.goodbye delete & .welcome delete``` *to remove!*",
            "SETVAR_DESC": "Set heroku config var",
            "SET_SUCCESS": "Successfully set ```{} ➜ {}```",
            "KEY_VAL_MISSING": "```Either Key or Value is missing```",
            "INVALID": "```Invalid key:value format```",
            "GETVAR_DESC": "Get heroku config var",
            "DELVAR_DESC": "Delete heroku config var",
            "DEL_SUCCESS": "```{} successfully deleted```",
            "NOT_FOUND": "```no results found for this key```",
            "SUCC": "*Successfully Setted Up ✅* \n*Please wait a little while.*",
            "SUCC_AF": "*To restore, use* ```default```",
            "DEGİS_NONE": "```Please Enter Any Module Name!``` \n\n*.degis afk*\n*.degis alive* << **Variables** >> \n_{pp}: You only need to use it once. Adds your profile photo to the message._ \n_{info}: Shows your status._ \n_{version}: Shows the version of the bot._ \n_{plugin}: Shows the plugin channel._\n*.degis ban*\n*.degis add*\n*.degis mute*\n*.degis unmute*\n*.degis promote*\n*.degis demote*\n*.degis welcome* \n*.degis goodbye* \n*.degis kickme*\n*.degis block*\n*.degis unblock*",
            "WR": "*Please use the modules that exists!*",
            "DEGİS_DESC": "Changes the text of modules like alive, afk etc.."       
        },       
        "covid": {
            "COV_DESC": "Shows the daily and overall covid table of more than 15 countries.",
            "NOT": "```Sorry I Could Not Find A Country Like This! Please Enter Applicable Country Codes!```\n\n```Country Codes:``` *.covid tr || az || usa || in || cn || nl || pk || ru || de || uk || gr || fr || jp || kz || id*"
        }
    }
}
